app = "gravity-lens"
primary_region = "bos"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[services]]
  protocol = "tcp"
  internal_port = 3001
  processes = ["app"]
  
  [[services.ports]]
    port = 3001
    handlers = ["http"]